### ISSUE TITLE
Fake issue for README.md

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/eg-telefonia-ui-arena-xtend#1]
![telefono](https://cloud.githubusercontent.com/assets/4549002/17305442/be221dbc-5800-11e6-90a9-e6391f58170f.png)

**Comment by PalumboN** [comment]
@fdodino Si querés usar github como repo de imágenes basta con solo arrastrarla (o copiarla) y esperar a que se suba (te aparece el link). No hace falta comentar / crear un issue falso :P
(INCREÍBLE que entré acá justamente para hacer eso! Jajajajaj)
